version: '3.9'

services:

  react-restaurant-pgdb:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 256mb
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: react_restaurant_db
      POSTGRES_PASSWORD: qazwsx

    ports: 
      - "12000:5432"

    volumes:
      - "./data:/var/lib/postgresql/data"